# the name of the target operating system
SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR arm)

# compilers for raspberry:
SET(CMAKE_C_COMPILER   arm-linux-gnueabihf-gcc)
SET(CMAKE_CXX_COMPILER arm-linux-gnueabihf-g++)
MESSAGE(STATUS "xxx: ${CMAKE_FIND_ROOT_PATH}")
MESSAGE(STATUS "yyy: ${CMAKE_SYSROOT}")
IF(NOT DEFINED CMAKE_SYSROOT)#TODO
    message(FATAL_ERROR "Specify CMAKE_SYSROOT variable!")
ENDIF(NOT DEFINED CMAKE_SYSROOT)
IF(NOT DEFINED CMAKE_FIND_ROOT_PATH)
    message(FATAL_ERROR "Specify CMAKE_FIND_ROOT_PATH variable!")
ENDIF(NOT DEFINED CMAKE_FIND_ROOT_PATH)

# if never -> searching programs just in host
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

# search headers and libraries in the target environment
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)